export enum SimulationActionType {
    GO_TO = 'GO_TO',
    CLICK_BY_TEXT = 'CLICK_BY_TEXT',
    WAIT_FOR_SELECTOR = 'WAIT_FOR_SELECTOR',
    WAIT_FOR_NAVIGATION = 'WAIT_FOR_NAVIGATION',
    WAIT_FOR_FUNCTION = 'WAIT_FOR_FUNCTION',
    WAIT_FOR_TIME = 'WAIT_FOR_TIME',
}
