/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
    auth: {
        users: UserAuthOperations;
    };
    collections: {
        pages: Page;
        users: User;
        posts: Post;
        resources: Resource;
        'resource-categories': ResourceCategory;
        'attribute-groups': AttributeGroup;
        attributes: Attribute;
        reviews: Review;
        'user-review-votes': UserReviewVote;
        media: Media;
        favourites: Favourite;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        pages: PagesSelect<false> | PagesSelect<true>;
        users: UsersSelect<false> | UsersSelect<true>;
        posts: PostsSelect<false> | PostsSelect<true>;
        resources: ResourcesSelect<false> | ResourcesSelect<true>;
        'resource-categories': ResourceCategoriesSelect<false> | ResourceCategoriesSelect<true>;
        'attribute-groups': AttributeGroupsSelect<false> | AttributeGroupsSelect<true>;
        attributes: AttributesSelect<false> | AttributesSelect<true>;
        reviews: ReviewsSelect<false> | ReviewsSelect<true>;
        'user-review-votes': UserReviewVotesSelect<false> | UserReviewVotesSelect<true>;
        media: MediaSelect<false> | MediaSelect<true>;
        favourites: FavouritesSelect<false> | FavouritesSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    globals: {
        settings: Settings;
        header: Header;
        footer: Footer;
    };
    globalsSelect: {
        settings: SettingsSelect<false> | SettingsSelect<true>;
        header: HeaderSelect<false> | HeaderSelect<true>;
        footer: FooterSelect<false> | FooterSelect<true>;
    };
    locale: 'en' | 'es' | 'de';
    user: User & {
        collection: 'users';
    };
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
    id: number;
    title: string;
    publishedDate?: string | null;
    content?: {
        root: {
            type: string;
            children: {
                type: string;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    slug?: string | null;
    meta?: {
        title?: string | null;
        description?: string | null;
        /**
         * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
         */
        image?: (number | null) | Media;
    };
    updatedAt: string;
    createdAt: string;
    _status?: ('draft' | 'published') | null;
}
/**
 * Uploaded media will be automatically optimized and resized.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    alt?: string | null;
    internalId?: string | null;
    caption?: {
        root: {
            type: string;
            children: {
                type: string;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        thumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        card?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    roles?: ('admin' | 'user')[] | null;
    updatedAt: string;
    createdAt: string;
    enableAPIKey?: boolean | null;
    apiKey?: string | null;
    apiKeyIndex?: string | null;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
    id: number;
    title: string;
    slug?: string | null;
    meta?: {
        title?: string | null;
        description?: string | null;
        /**
         * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
         */
        image?: (number | null) | Media;
    };
    updatedAt: string;
    createdAt: string;
    _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
    id: number;
    name: string;
    featuredImage?: (number | null) | Media;
    slug?: string | null;
    summary?: string | null;
    content?: {
        root: {
            type: string;
            children: {
                type: string;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    contentRawText?: string | null;
    websiteUrl?: string | null;
    affiliateLink?: string | null;
    categories?: (number | ResourceCategory)[] | null;
    avgReviewPoint?: number | null;
    totalReview?: number | null;
    attributes?: (number | Attribute)[] | null;
    meta?: {
        title?: string | null;
        description?: string | null;
        /**
         * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
         */
        image?: (number | null) | Media;
    };
    updatedAt: string;
    createdAt: string;
    _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-categories".
 */
export interface ResourceCategory {
    id: number;
    name: string;
    slug?: string | null;
    parent?: (number | null) | ResourceCategory;
    resources?: (number | Resource)[] | null;
    meta?: {
        title?: string | null;
        description?: string | null;
        /**
         * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
         */
        image?: (number | null) | Media;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
    id: number;
    name: string;
    slug?: string | null;
    description?: string | null;
    attributeGroup: number | AttributeGroup;
    order?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups".
 */
export interface AttributeGroup {
    id: number;
    name: string;
    slug?: string | null;
    description?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
    id: number;
    point: number;
    comment?: string | null;
    resource: number | Resource;
    user: number | User;
    helpfulCount?: number | null;
    helplessCount?: number | null;
    helpfulRating?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-review-votes".
 */
export interface UserReviewVote {
    id: number;
    user: number | User;
    review: number | Review;
    isHelpful: boolean;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourites".
 */
export interface Favourite {
    id: number;
    user: number | User;
    resource: number | Resource;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: 'pages';
              value: number | Page;
          } | null)
        | ({
              relationTo: 'users';
              value: number | User;
          } | null)
        | ({
              relationTo: 'posts';
              value: number | Post;
          } | null)
        | ({
              relationTo: 'resources';
              value: number | Resource;
          } | null)
        | ({
              relationTo: 'resource-categories';
              value: number | ResourceCategory;
          } | null)
        | ({
              relationTo: 'attribute-groups';
              value: number | AttributeGroup;
          } | null)
        | ({
              relationTo: 'attributes';
              value: number | Attribute;
          } | null)
        | ({
              relationTo: 'reviews';
              value: number | Review;
          } | null)
        | ({
              relationTo: 'user-review-votes';
              value: number | UserReviewVote;
          } | null)
        | ({
              relationTo: 'media';
              value: number | Media;
          } | null)
        | ({
              relationTo: 'favourites';
              value: number | Favourite;
          } | null);
    globalSlug?: string | null;
    user: {
        relationTo: 'users';
        value: number | User;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user: {
        relationTo: 'users';
        value: number | User;
    };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
    title?: T;
    publishedDate?: T;
    content?: T;
    slug?: T;
    meta?:
        | T
        | {
              title?: T;
              description?: T;
              image?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    roles?: T;
    updatedAt?: T;
    createdAt?: T;
    enableAPIKey?: T;
    apiKey?: T;
    apiKeyIndex?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
    title?: T;
    slug?: T;
    meta?:
        | T
        | {
              title?: T;
              description?: T;
              image?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
    name?: T;
    featuredImage?: T;
    slug?: T;
    summary?: T;
    content?: T;
    contentRawText?: T;
    websiteUrl?: T;
    affiliateLink?: T;
    categories?: T;
    avgReviewPoint?: T;
    totalReview?: T;
    attributes?: T;
    meta?:
        | T
        | {
              title?: T;
              description?: T;
              image?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-categories_select".
 */
export interface ResourceCategoriesSelect<T extends boolean = true> {
    name?: T;
    slug?: T;
    parent?: T;
    resources?: T;
    meta?:
        | T
        | {
              title?: T;
              description?: T;
              image?: T;
          };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups_select".
 */
export interface AttributeGroupsSelect<T extends boolean = true> {
    name?: T;
    slug?: T;
    description?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
    name?: T;
    slug?: T;
    description?: T;
    attributeGroup?: T;
    order?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
    point?: T;
    comment?: T;
    resource?: T;
    user?: T;
    helpfulCount?: T;
    helplessCount?: T;
    helpfulRating?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-review-votes_select".
 */
export interface UserReviewVotesSelect<T extends boolean = true> {
    user?: T;
    review?: T;
    isHelpful?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    internalId?: T;
    caption?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              thumbnail?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              card?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourites_select".
 */
export interface FavouritesSelect<T extends boolean = true> {
    user?: T;
    resource?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
    id: number;
    homeTitle: string;
    homeDescription?: string | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
    id: number;
    navItems?:
        | {
              link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                  } | null;
                  url?: string | null;
                  label: string;
              };
              id?: string | null;
          }[]
        | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
    id: number;
    navItems?:
        | {
              link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                  } | null;
                  url?: string | null;
                  label: string;
              };
              id?: string | null;
          }[]
        | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
    homeTitle?: T;
    homeDescription?: T;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
    navItems?:
        | T
        | {
              link?:
                  | T
                  | {
                        type?: T;
                        newTab?: T;
                        reference?: T;
                        url?: T;
                        label?: T;
                    };
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
    navItems?:
        | T
        | {
              link?:
                  | T
                  | {
                        type?: T;
                        newTab?: T;
                        reference?: T;
                        url?: T;
                        label?: T;
                    };
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}
