name: Orien Trade BE

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Docker provider'
        required: true
        default: 'docker'
        type: choice
        options:
        - docker
      registry:
        description: 'Docker provider'
        required: true
        default: 'zodinettech'
      service:
        description: 'Service name'
        required: true
        default: 'orien-trade-backend'
      worker_service:
        description: 'Worker service'
        required: false
        default: ''
        type: choice
        options:
        - ''
        - orien-trade-worker-01

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get tag name
        id: get_tag
        run: |
          VERSION="${{ github.run_number }}"
          DOCKER_TAGS="${{ inputs.registry }}/${{ inputs.service }}:${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_ENV
          echo "build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: ${{ inputs.provider == 'docker' }} 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.docker_tags }}
          build-args: |
            SWAGGER_VERSION=${{ env.version }}
            BUILD_DATE=${{ env.build_date }}
            VCS_REF=${{ github.sha }}

  deploy:
    name: Deploy
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          VERSION="${{ github.run_number }}"
          DOCKER_TAGS="${{ inputs.registry }}/${{ inputs.service }}:${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_ENV

      - name: Deploy Main Service
        uses: floms/action-caprover@v1
        with:
          host: ${{secrets.CAPROVER_SERVER_DEV}}
          password: ${{secrets.CAPROVER_PASSWORD_DEV}}
          app: ${{ inputs.service }}
          image: ${{ env.docker_tags }}

      - name: Deploy Worker Service
        if: ${{ inputs.worker_service != '' }}
        uses: floms/action-caprover@v1
        with:
          host: ${{secrets.CAPROVER_SERVER_DEV}}
          password: ${{secrets.CAPROVER_PASSWORD_DEV}}
          app: ${{ inputs.worker_service }}
          image: ${{ env.docker_tags }}
